version: '3.8'

services:
  mysql:
    image: docker.io/library/mysql:8.0
    container_name: mysql_server
    environment:
      # Sensitive information like passwords should be set in environment variables
      # rather than hardcoding them in the docker-compose.yml file.
      # You can use a .env(check module root) file to manage these variables.
      # With this config user is: "root"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app_network
    # Health check ensures that the MySQL service is ready
    # before phpMyAdmin tries to connect to it.
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 5
    restart: always

  spring-boot-app:
    image: docker.io/phpmyadmin/phpmyadmin:latest
    container_name: spring_boot_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8081:8080"
    networks:
      - app_network
    depends_on:
      mysql:
        condition: service_healthy

    restart: always

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
