package com.developer.java.custom;

import lombok.Getter;
import org.jetbrains.annotations.NotNull;

@Getter
public enum WorldCapital {
  KABUL("Kabul", "Afghanistan"),
  TIRANA("Tirana", "Albania"),
  ALGIERS("Algiers", "Algeria"),
  ANDORRA_LA_VELLA("Andorra la Vella", "Andorra"),
  LUANDA("Luanda", "Angola"),
  SAINT_JOHNS("Saint John's", "Antigua and Barbuda"),
  BUENOS_AIRES("Buenos Aires", "Argentina"),
  YEREVAN("Yerevan", "Armenia"),
  CANBERRA("Canberra", "Australia"),
  VIENNA("Vienna", "Austria"),
  BAKU("Baku", "Azerbaijan"),
  NASSAU("Nassau", "Bahamas"),
  MANAMA("Manama", "Bahrain"),
  DHAKA("Dhaka", "Bangladesh"),
  BRIDGETOWN("Bridgetown", "Barbados"),
  MINSK("Minsk", "Belarus"),
  BRUSSELS("Brussels", "Belgium"),
  BELMOPAN("Belmopan", "Belize"),
  PORTO_NOVO("Porto-Novo", "Benin"),
  THIMPHU("Thimphu", "Bhutan"),
  SUCRE("Sucre", "Bolivia"),
  SARAJEVO("Sarajevo", "Bosnia and Herzegovina"),
  GABORONE("Gaborone", "Botswana"),
  BRASILIA("Brasília", "Brazil"),
  BANDAR_SERI_BEGAWAN("Bandar Seri Begawan", "Brunei"),
  SOFIA("Sofia", "Bulgaria"),
  OUAGADOUGOU("Ouagadougou", "Burkina Faso"),
  GITEGA("Gitega", "Burundi"),
  PRAIA("Praia", "Cabo Verde"),
  PHNOM_PENH("Phnom Penh", "Cambodia"),
  YAOUNDE("Yaoundé", "Cameroon"),
  OTTAWA("Ottawa", "Canada"),
  BANGUI("Bangui", "Central African Republic"),
  NDJAMENA("N'Djamena", "Chad"),
  SANTIAGO("Santiago", "Chile"),
  BEIJING("Beijing", "China"),
  BOGOTA("Bogotá", "Colombia"),
  MORONI("Moroni", "Comoros"),
  KINSHASA("Kinshasa", "Congo, Democratic Republic of the"),
  BRAZZAVILLE("Brazzaville", "Congo, Republic of the"),
  SAN_JOSE("San José", "Costa Rica"),
  ZAGREB("Zagreb", "Croatia"),
  HAVANA("Havana", "Cuba"),
  NICOSIA("Nicosia", "Cyprus"),
  PRAGUE("Prague", "Czech Republic"),
  COPENHAGEN("Copenhagen", "Denmark"),
  DJIBOUTI("Djibouti", "Djibouti"),
  ROSEAU("Roseau", "Dominica"),
  SANTO_DOMINGO("Santo Domingo", "Dominican Republic"),
  QUITO("Quito", "Ecuador"),
  CAIRO("Cairo", "Egypt"),
  SAN_SALVADOR("San Salvador", "El Salvador"),
  MALABO("Malabo", "Equatorial Guinea"),
  ASMARA("Asmara", "Eritrea"),
  TALLINN("Tallinn", "Estonia"),
  MBABANE("Mbabane", "Eswatini"),
  ADDIS_ABABA("Addis Ababa", "Ethiopia"),
  SUVA("Suva", "Fiji"),
  HELSINKI("Helsinki", "Finland"),
  PARIS("Paris", "France"),
  LIBREVILLE("Libreville", "Gabon"),
  BANJUL("Banjul", "Gambia"),
  TBILISI("Tbilisi", "Georgia"),
  BERLIN("Berlin", "Germany"),
  ACCRA("Accra", "Ghana"),
  ATHENS("Athens", "Greece"),
  SAINT_GEORGES("Saint George's", "Grenada"),
  GUATEMALA_CITY("Guatemala City", "Guatemala"),
  CONAKRY("Conakry", "Guinea"),
  BISSAU("Bissau", "Guinea-Bissau"),
  GEORGETOWN("Georgetown", "Guyana"),
  PORT_AU_PRINCE("Port-au-Prince", "Haiti"),
  TEGUCIGALPA("Tegucigalpa", "Honduras"),
  BUDAPEST("Budapest", "Hungary"),
  REYKJAVIK("Reykjavik", "Iceland"),
  NEW_DELHI("New Delhi", "India"),
  JAKARTA("Jakarta", "Indonesia"),
  TEHRAN("Tehran", "Iran"),
  BAGHDAD("Baghdad", "Iraq"),
  DUBLIN("Dublin", "Ireland"),
  JERUSALEM("Jerusalem", "Israel"),
  ROME("Rome", "Italy"),
  KINGSTON("Kingston", "Jamaica"),
  TOKYO("Tokyo", "Japan"),
  AMMAN("Amman", "Jordan"),
  NUR_SULTAN("Nur-Sultan", "Kazakhstan"),
  NAIROBI("Nairobi", "Kenya"),
  TARAWA("Tarawa", "Kiribati"),
  PRISTINA("Pristina", "Kosovo"),
  KUWAIT_CITY("Kuwait City", "Kuwait"),
  BISHKEK("Bishkek", "Kyrgyzstan"),
  VIENTIANE("Vientiane", "Laos"),
  RIGA("Riga", "Latvia"),
  BEIRUT("Beirut", "Lebanon"),
  MASERU("Maseru", "Lesotho"),
  MONROVIA("Monrovia", "Liberia"),
  TRIPOLI("Tripoli", "Libya"),
  VILNIUS("Vilnius", "Lithuania"),
  LUXEMBOURG_CITY("Luxembourg City", "Luxembourg"),
  ANTANANARIVO("Antananarivo", "Madagascar"),
  LILONGWE("Lilongwe", "Malawi"),
  KUALA_LUMPUR("Kuala Lumpur", "Malaysia"),
  MALE("Malé", "Maldives"),
  BAMAKO("Bamako", "Mali"),
  VALLETTA("Valletta", "Malta"),
  MAJURO("Majuro", "Marshall Islands"),
  NOUAKCHOTT("Nouakchott", "Mauritania"),
  PORT_LOUIS("Port Louis", "Mauritius"),
  MEXICO_CITY("Mexico City", "Mexico"),
  PALIKIR("Palikir", "Micronesia"),
  CHISINAU("Chisinau", "Moldova"),
  MONACO("Monaco", "Monaco"),
  ULAANBAATAR("Ulaanbaatar", "Mongolia"),
  PODGORICA("Podgorica", "Montenegro"),
  RABAT("Rabat", "Morocco"),
  MAPUTO("Maputo", "Mozambique"),
  NAYPYIDAW("Naypyidaw", "Myanmar"),
  WINDHOEK("Windhoek", "Namibia"),
  YAREN("Yaren", "Nauru"),
  KATHMANDU("Kathmandu", "Nepal"),
  AMSTERDAM("Amsterdam", "Netherlands"),
  WELLINGTON("Wellington", "New Zealand"),
  MANAGUA("Managua", "Nicaragua"),
  NIAMEY("Niamey", "Niger"),
  ABUJA("Abuja", "Nigeria"),
  PYONGYANG("Pyongyang", "North Korea"),
  SKOPJE("Skopje", "North Macedonia"),
  OSLO("Oslo", "Norway"),
  MUSCAT("Muscat", "Oman"),
  ISLAMABAD("Islamabad", "Pakistan"),
  NGERULMUD("Ngerulmud", "Palau"),
  PANAMA_CITY("Panama City", "Panama"),
  PORT_MORESBY("Port Moresby", "Papua New Guinea"),
  ASUNCION("Asunción", "Paraguay"),
  LIMA("Lima", "Peru"),
  MANILA("Manila", "Philippines"),
  WARSAW("Warsaw", "Poland"),
  LISBON("Lisbon", "Portugal"),
  DOHA("Doha", "Qatar"),
  BUCHAREST("Bucharest", "Romania"),
  MOSCOW("Moscow", "Russia"),
  KIGALI("Kigali", "Rwanda"),
  BASSETERRE("Basseterre", "Saint Kitts and Nevis"),
  CASTRIES("Castries", "Saint Lucia"),
  KINGSTOWN("Kingstown", "Saint Vincent and the Grenadines"),
  APIA("Apia", "Samoa"),
  SAN_MARINO("San Marino", "San Marino"),
  SAO_TOME("São Tomé", "São Tomé and Príncipe"),
  RIYADH("Riyadh", "Saudi Arabia"),
  DAKAR("Dakar", "Senegal"),
  BELGRADE("Belgrade", "Serbia"),
  VICTORIA("Victoria", "Seychelles"),
  FREETOWN("Freetown", "Sierra Leone"),
  SINGAPORE("Singapore", "Singapore"),
  BRATISLAVA("Bratislava", "Slovakia"),
  LJUBLJANA("Ljubljana", "Slovenia"),
  HONIARA("Honiara", "Solomon Islands"),
  MOGADISHU("Mogadishu", "Somalia"),
  PRETORIA("Pretoria", "South Africa"),
  SEOUL("Seoul", "South Korea"),
  JUBA("Juba", "South Sudan"),
  MADRID("Madrid", "Spain"),
  COLOMBO("Colombo", "Sri Lanka"),
  KHARTOUM("Khartoum", "Sudan"),
  PARAMARIBO("Paramaribo", "Suriname"),
  STOCKHOLM("Stockholm", "Sweden"),
  BERN("Bern", "Switzerland"),
  DAMASCUS("Damascus", "Syria"),
  TAIPEI("Taipei", "Taiwan"),
  DUSHANBE("Dushanbe", "Tajikistan"),
  DODOMA("Dodoma", "Tanzania"),
  BANGKOK("Bangkok", "Thailand"),
  LOME("Lomé", "Togo"),
  NUKU_ALOFA("Nuku'alofa", "Tonga"),
  PORT_OF_SPAIN("Port of Spain", "Trinidad and Tobago"),
  TUNIS("Tunis", "Tunisia"),
  ANKARA("Ankara", "Turkey"),
  ASHGABAT("Ashgabat", "Turkmenistan"),
  FUNAFUTI("Funafuti", "Tuvalu"),
  KAMPALA("Kampala", "Uganda"),
  KYIV("Kyiv", "Ukraine"),
  ABU_DHABI("Abu Dhabi", "United Arab Emirates"),
  LONDON("London", "United Kingdom"),
  WASHINGTON_DC("Washington, D.C.", "United States"),
  MONTEVIDEO("Montevideo", "Uruguay"),
  TASHKENT("Tashkent", "Uzbekistan"),
  PORT_VILA("Port Vila", "Vanuatu"),
  VATICAN_CITY("Vatican City", "Vatican City"),
  CARACAS("Caracas", "Venezuela"),
  HANOI("Hanoi", "Vietnam"),
  SANAA("Sanaa", "Yemen"),
  LUSAKA("Lusaka", "Zambia"),
  HARARE("Harare", "Zimbabwe");

  private final String capitalName;
  private final String countryName;

  WorldCapital(String capitalName, String countryName) {
    this.capitalName = capitalName;
    this.countryName = countryName;
  }

  @Override
  public @NotNull String toString() {
    return capitalName + " is the capital of " + countryName + "\n";
  }
}
